export const metadata = {
    title: 'Daktilo Iframe Carousel',
    description: 'Generated by Prodestek',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
